swagger: "2.0"
info:
  description: "Document Scanner API reference"
  version: "1.0.0"
  title: "Document Scanner"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "MIT"
    url: "https://github.com/RichTeaMan/DocumentScanner/blob/master/license.txt"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /scan:
    post:
      summary: "Scans a document"
      description: ""
      operationId: "scanDocument"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - in: formData
        name: "document"
        type: "string"
        description: "Document to scan"
        required: true
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/ScanResponse"
        400:
          description: "Invalid input"
definitions:
  Token:
    type: "object"
    properties:
      dep:
        type: "string"
      isAlpha:
        type: "boolean"
      isStop:
        type: "boolean"
      lemma:
        type: "string"
      pos:
        type: "string"
      shape:
        type: "string"
      tag:
        type: "string"
      text:
        type: "string"
    xml:
      name: "Order"
  ScanResponse:
    type: "object"
    properties:
      tokens:
        type: "array"
        items:
          $ref: "#/definitions/Token"